### ISSUE TITLE
socket.connect does not appear to be thread safe

### ISSUE THREAD

**Issue by mikejr** [DataDog/datadogpy#109]
Seeing a lot of socket errors logged by **DogStatsd** when running multiple threads. The issue appears to be related to the use of `socket.connect` with `socket.send`.  The alternative, `socket.sendto`, should fix the issue.

The following is a simplification of the flow, but consistently reproduces the issue.

```python
import threading
import socket

class WithConnect(object):

    def __init__(self):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.connect(('127.0.0.1', 9991))
        self.error_count = 0

    def run(self):
        try:
            self.sock.send('hi')
        except:
            self.error_count += 1

class WithoutConnect(object):

    def __init__(self):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.error_count = 0

    def run(self):
        try:
            self.sock.sendto('hi', ('127.0.0.1', 9990))
        except:
            self.error_count += 1

wc = WithConnect()
woc = WithoutConnect()

def main():
    wc.run()
    woc.run()

threads = [
    threading.Thread(target=main)
    for i in range(100)
]

map(lambda t: t.start(), threads)
map(lambda t: t.join(), threads)

print 'WithConnect.error_count = %d' % wc.error_count
print 'WithoutConnect.error_count = %d' % woc.error_count
```

**Comment by yannmh** [comment]
Thank you for such a detailed feedback @mikejr ! 
We'll spend more time looking at this during the next few days to bring the appropriate modifications.

**Comment by yannmh** [comment]
Hi @mikejr,

I have been running more tests, but I am unable to identify any thread safety related issue.
While running your snippet, I only see `[Errno 61] Connection refused` exception raised when `socket.connect` is used.


### About `[Errno 61] Connection refused`

This message indicates that an ICMP Destination Unreachable response has been received in reply to a packet sent to an unbound port on the server. 

This is an expected behavior here:  in a "connected" mode, the socket would report (with enough delay to receive it) any ICMP response. Thus, I see the same exception when using a single thread and a few seconds wait between two `socket.send` calls. At the opposite, I see no exceptions, when `socket.connect` targets to a listening port.


@mikejr can you confirm that you are seing the same exception ? If so, we should investigate on the host side to understand why it becomes unreachable (defficient, restarting DogStatsd server ?).


Yann

**Comment by mikejr** [comment]
@yannmh Yep, thats the same error and it does occur when DogStatsd is unavailable. I was trying to avoid spamming the logs when shutting down DogStatsd. Will take another route. Thanks for looking into it.

**Comment by yannmh** [comment]
Thanks for confirming. 
I am closing the issue. Please feel free to reopen if needed.
