### ISSUE TITLE
SyntaxError with Python 3.4

### ISSUE THREAD

**Issue by ksrm** [DataDog/datadogpy#165]
$ sudo pip3 install datadog
    Downloading/unpacking datadog
      Downloading datadog-0.14.0.tar.gz
      Running setup.py (path:/tmp/pip_build_root/datadog/setup.py) egg_info for package datadog

    Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.2 in /usr/local/lib/python3.4/dist-packages (from datadog)
    Requirement already satisfied (use --upgrade to upgrade): requests>=2.6.0 in /usr/local/lib/python3.4/dist-packages (from datadog)
    Requirement already satisfied (use --upgrade to upgrade): simplejson>=3.0.0 in /usr/local/lib/python3.4/dist-packages (from datadog)
    Installing collected packages: datadog
      Running setup.py install for datadog
          File "/usr/local/lib/python3.4/dist-packages/datadog/dogstatsd/context_async.py", line 16
            async def wrapped_co(*args, **kwargs):
                ^
        SyntaxError: invalid syntax

        Installing dogwrap script to /usr/local/bin
        Installing dog script to /usr/local/bin
    Successfully installed datadog
    Cleaning up...

**Comment by yannmh** [comment]
Thanks for reporting @ksrm.

I am taking a look at it 👀  This path should be imported with Python > 3.5 only.

**Comment by yannmh** [comment]
@ksrm, 

This error is harmless and can be ignored.  

This happens when `pip` attempts to byte-compile a file which contains some code syntax specific to a given version of Python.  In this case, `datadog/dogstatsd/context_async.py` is specific to (and imported only with) Python > 3.5, hence the failure. 

Recent versions of `pip` should have this issue "fixed" by silencing those exceptions when the build is successful:  https://github.com/pypa/pip/issues/1873.
