### ISSUE TITLE
ThreadStats object does nothing if using mixed multiprocessing and threading

### ISSUE THREAD

**Issue by wolftrouble** [DataDog/datadogpy#214]
I can supply a code snippet example if need be, but the basics are: In my code I'm using the multiprocessing module to create and manage a pool of Multiprocessing.Process() workers. Those workers, in turn, each have their own datadog.ThreadStats instance they create for themselves on object init.

The problem is that in this configuration the ThreadStats() object does nothing. No metrics every show up in dogstatsd (and in fact both the forwarder and the daemon report basically no traffic), there are no flush messages in the logs, etc. Even if I flip flush_in_thread=False and try to manually call flush() nothing happens. It's as if the dogstats module isn't even used. No exceptions are thrown.

If on the other hand I convert the workers into Threading.Thread() workers - and make no other changes, because Multiprocessing is intended to be a drop-in API replacement for Threading - everything works fine.

There shouldn't be anything inherently wrong with using (as in, some code makes use of one, some makes use of the other) both these two modules, from my understanding. I tried to dig into what might be happening with no luck, for example, is ThreadStats accidentally calling Multiprocessing methods, despite explicitly instantiating Threading.Thread object?
 (https://github.com/DataDog/datadogpy/blob/master/datadog/threadstats/periodic_timer.py#L9).  Doesn't look like it, but that's my current suspicion.

**Comment by wolftrouble** [comment]
Disregard, the problem is I was trying to create the ThreadStats() object in the multiprocessing.Process object's init() function. That apparently won't work, and moving both the object creation and start to the Process object's run() function solved the problem.

**Comment by ava-dylang** [comment]
in my case, TheadStats was shared to the multiprocessing pool worker threads before the process was forked; so metrics reported were saved in the thread's copy of the metrics aggregator; normally this aggregator is flushed at the end of the whole python runtime, but when my thread are closed, so too is thier copy of the metrics they generated; I found someone post a workaround that if they slept for the time it takes metrics to autoflush, they would autoflush and be kept; but also looking at the TheadStat source revealed that the datadog official hack to flush metrics early is to call threadstat.flush with infinity like so

    theadstats.flush(float('inf'))

calling this inside each multiprocessing worker thread caused the metrics generated in that thread to independently flush and post to datadog; this is a little bit shitty because we're making O(N) calls to the datadog api based on worker count; if I had a lot of workers I would want some way to merge the rollup

a better bet might be to convert threadstat's metrics agregator metrics list to a multiprocessing shared data list
