### ISSUE TITLE
Make possible get Rate Limit headers values

### ISSUE THREAD

**Issue by xkrt** [DataDog/datadogpy#219]
Some Datadog REST API endpoints are rate limited.
Make it possible to get current rate limits. Most interesting methods for me is:
`datadog.api.Metric.query()`
`datadog.api.Metric.send()`

**Comment by jgrobbel** [comment]
Not that I just want to just +1 here (I do). But the official docs do suggest we should be able to get them in python:
https://docs.datadoghq.com/api/?lang=python#rate-limiting

Since queries are rate limited to 300 per hour, returning these headers will be of great value for the application to take corrective action.

**Comment by gzussa** [comment]
This pr should solve this issue https://github.com/DataDog/datadogpy/pull/378
