### ISSUE TITLE
Metrics emitted by `statsd.timing` arrive in datadog as gauge without unit

### ISSUE THREAD

**Issue by weilu** [DataDog/datadogpy#229]
Judging from the code, [`statsd.timing` is reported with unit 'ms'](https://github.com/DataDog/datadogpy/blob/8b19b0b6e2d5e898dc05800f8257430b68156471/datadog/dogstatsd/base.py#L198), but when it reaches datadog, judging form the UI it appears that the unit is not defined:

<img width="217" alt="screen shot 2017-09-07 at 6 14 40 pm" src="https://user-images.githubusercontent.com/412533/30158717-b548657c-93f8-11e7-88d0-7b7f7c92f972.png">

It can be confusing as the `statsd.timing` method doesn't respect the `use_ms` configuration passed into the `DogStatsd` constructor and always uses ms. If one uses the default `DogStatsd` and uses both `@timed` and `timing` without conversion, one is bound to be surprised by the outcome if they didn't read the implementation. I guess "always using ms for timing" is by design to be consistent with the statsd package's `timing` interface. Then perhaps the least we can do is to pass the unit correctly to datadog UI to minimize confusion. Thoughts?

I'm not sure where the unit `ms` is dropped (or if it's just a datadog UI issue). If anyone can point me to the right place I'm happy to make a PR.

**Comment by weilu** [comment]
Ping! Any update on this?

**Comment by radzhome** [comment]
+1

**Comment by j-manu** [comment]
This is either a bug with the dog-statsd server or with datadoghq.com. The same problem exists with the datadog ruby library also.

**Comment by jbayardo** [comment]
+1

**Comment by radifalco** [comment]
+1 Please. It's a drag to have to go into the UI and set the Units to milliseconds for each custom timing metric.

**Comment by robdennis** [comment]
I had been acting on the impression that ``timed`` was in milliseconds and configured it appropriately in the Metrics Summary section of the app. I ended up needing to suss out an issue where my instrumented application combined ``timed`` and ``timing`` metrics and the scales seemed wrong.

Here's a test program I wrote (where ``client`` is an initialized dogstatsd client from this library:
```
if __name__ == '__main__':

        for secs in [1, 3, 5, 10, 20]:

                with client.timed('timed'):
                        start_monotonic = time.monotonic()
                        start_time = time.time()

                        time.sleep(secs)

                        end_monotonic = time.monotonic() - start_monotonic
                        end_time = time.time() - start_time
                        print(f'monotonic: {end_monotonic} - time: {end_time}')
                        client.timing('timing.time', end_time)
                        client.timing('timing.monotonic', end_monotonic)
                        client.timing('timing.time_x1000', end_time * 1000)
                        client.timing('timing.monotonic_x1000', end_monotonic * 1000)
```

I was surprised to see that the unconfigured values that ended up in the metrics explorer were (paraphrasing):
- timed: 20
- timing.time: 20
- timing.monotonic: 20
- timing.time_x1000: 20k
- timing.monotonic_x1000: 20k

which implies that ``timed `` / ``timing`` actually should have both been configured as seconds here. And x1000 as milliseconds

Something I need to pay attention to in the future.

**Comment by eoinmorgan** [comment]
+1

**Comment by komuw** [comment]
@yannmh 

Hi, is this something that datadog intends to have solved? 
I could send a patch if I'm pointed in the right direction.

**Comment by komuw** [comment]
cc @nmuesch @zippolyte

**Comment by zippolyte** [comment]
Hello all ! Very sorry for not having updated this thread before. 

So, as you can see below, the `"ms"` that you see in the call to `_report` is not actually the metric unit. It is the metric type, and it is used by the dogstatsd server to identify which type of metric you are trying to send. https://github.com/DataDog/datadogpy/blob/8b19b0b6e2d5e898dc05800f8257430b68156471/datadog/dogstatsd/base.py#L244

Timers in dogstatsd are simply histograms, as stated in [this documentation](https://docs.datadoghq.com/developers/dogstatsd/data_types/#timers), and as you can see in here in the dogstatsd server implementation https://github.com/DataDog/datadog-agent/blob/3a0c649347cca9eb40f087f98f94b384cdba9747/pkg/dogstatsd/parser.go#L33.

There is no unit attached to what you are sampling, and it's up to the one instrumenting the code to know what they are measuring, seconds or milliseconds. You could even send hours or days or anything really by using the `timing()` method directly since in the end it will just be a histogram of the values you sampled.

The `use_ms` parameter is only used when using the [`timed` decorator](https://docs.datadoghq.com/developers/dogstatsd/data_types/#timers). Using this, then you know that what is sent will be millisseconds is `use_ms` is `True`, and seconds otherwise, but you would still have to set the unit in datadog manually unfortunately. There is no way to have automatic units for custom metrics.

I hope I've answered all the questions here. Let me know if it's not the case.

**Comment by januszm** [comment]
I think it is worth explaining this situation a little better, i.e., add information on the `timed` [documentation page](https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=python#timer) about the fact that the unit is not set, but in the case of the code as below, (or in the example from the docs) it will be `seconds`.

```python
@statsd.timed("test_metric.timer")
def test_sleep():
    time.sleep(5)

# this will sleep for 5 seconds
# datadoghq dashboard will present this as data point with value 5
```

**Comment by januszm** [comment]
@hush-hush one year after this issue was closed, it is still not clear from the documentation how to set the correct time unit when sending a metric or setting it up on a chart.
Today I tried again to send function execution time metrics to Datadog, this time from a Ruby application, and the following trivial piece of code:

```ruby
$statsd.time('test.time') { sleep 5 }
```

results in 5000 (5K) being shown in the Datadog graph. Maybe I'm missing some information, but it seems that It is not possible to correct the unit on the graph (no option to change from `ms` to `seconds` or vice versa).

**Comment by sgnn7** [comment]
Hey @januszm,
Maybe it will be worth it to explain a bit what's going on at each level since it may not be obvious:
- Python client by default uses elapsed seconds in timing data that it forwards to the agent (eg. `time.sleep(2)` duration is sent as a `2.0`).
- If you set `use_ms=True` in the decorator or the constructor of your instance of `DogStatsd`, the data is sent as milliseconds (eg. `time.sleep(2)` duration is sent as a `2000.0`).
- When using `statsd` module-level instance, you can do `statsd.use_ms` to toggle this.
- `statsd.timing` doesn't have `use_ms` because it's user provided and the value can be changed (n*1000 to send `ms` value) before it's passed in.
- As @zippolyte mentioned, neither the Agent nor the DDOG backend know what units these values are in (they just get a number (`2.0` or `2000.0` from our examples). Because of this, manual setting of the units on the metric in the UI is required.
- As for the Ruby library, there may be differences in implementations between client libraries. 
  - These differences between libraries could be something that can be worked on if needed.

If the library is not doing what you expect given the list above, we can try to fix it up but overall the main thing to keep in mind is that the backend only sees numbers without units.

Hopefully this helps,
Srdjan
