### ISSUE TITLE
ThreadStats thread cleanup

### ISSUE THREAD

**Issue by leanne73** [DataDog/datadogpy#300]
Hello,
We’re running Datadog ThreadStats (using the flush_in_thread setting) in a script on a Kubernetes pod and we’ve recently been encountering intermittent issues where we’ve seen our script finish, yet the pod fail to change to a Failed/Succeeded state. This has happened both when an exception is raised which should terminate the script and when the script finishes successfully. This pod has only a single container running the python script with threadstats. The only reason why the container should not change to a failed/succeeded state is if there is still a thread active in the container. What handles cleanup of the Datadog ThreadStats thread? Could it still remain active in some cases when the main thread has ended? We haven’t seen any way to invoke cleanup manually and are considering moving to using flush_in_process and/or a hard os.exit when we terminate instead, but would like to know what's going on.

**Comment by zippolyte** [comment]
Hello @leanne73,

Sorry for answering this late, are you still having this issue ?
Have you called the `stop()` method on your threadstats object before exiting your script ?

**Comment by zippolyte** [comment]
@leanne73 
Cleanup of the threads should be done by calling `threadstats.stop()`. This is up to the caller to call this, so you should do that in a `finally` block so that it is called even in case there is an exception in your app.
Closing this issue, feel free to reopen if you are encountering the problem even by calling `stop()`
