### ISSUE TITLE
DNS re-resolution if host IP changes

### ISSUE THREAD

**Issue by opb** [DataDog/datadogpy#320]
Hi there

I'm trying to understand a failure mode we've spotted. Out python app was configured to connect to the DNS host for the dogstatsd endpoint. At some point while the app was running, the collector IP address changes (along with the DNS accordingly) but we stopped receiving data from the python application.

It appears as if DNS resolution happened as a one-time thing when the app booted, and it subsequently used that IP, without trying to re-resolve. Is this expected?

Thanks

**Comment by zippolyte** [comment]
Hi @opb,

Sorry for not answering sooner, but yeah this would be expected.
This is inherent to the fact that dogstatsd metrics are sent through a UDP connection. 
Once the IP address has been resolved when first establishing the connection, the UDP connection will stay open until we hit a failure, at which point it is reset thanks to this code https://github.com/DataDog/datadogpy/blob/b829d13f3f81cc9c92661a1cddf324aaba9f75c8/datadog/dogstatsd/base.py#L324-L336.
Problem is, since this is UDP, even if the dogstatsd server has changed IP address and there is nothing at the end of the connection to receive the UDP messages, sending them will not result in a failure.

One way to mitigate this would be to manually close the connection (by calling `statsd.close_socket()` in your instrumented app) so that a new one is created when the next dogstatsd message needs to be sent.
Is it expected that your dogstatsd server IP address changes often ?

**Comment by zippolyte** [comment]
Since this is expected and tied to how the UDP protocol works, I'm closing this issue.

**Comment by bentheiii** [comment]
Hello, is there any way to fix this within datadogpy, maybe by setting a TTL on socket connections, having them automatically close when the time is up? This is necessary in orchestrated environments, where the DD agent and server may terminate and re-start (with the same hostname, but not same IP) at any time.
I'd like to create a PR for this solution, if it is acceptable.
