### ISSUE TITLE
Datadog's Lambda Layer

### ISSUE THREAD

**Issue by dmksnnk** [DataDog/datadogpy#350]
Hi, in [this article](https://www.datadoghq.com/blog/datadog-lambda-layer/) `lambda_metric`  exposes only distributions. So I have few questions:
 - Why expose only distributions for Lambda?
-  What is a correct way to use DataDog's layer if I would like to send other metrics too?

I have tried:
```python
from datadog.threadstats.aws_lambda import _lambda_stat
...
@datadog_lambda_wrapper
def handler(event, context):
    _lambda_stats.increment("some_metric")
```

and it works pretty well, but does't look like a correct way of doing.

Thanks, Dmytro

**Comment by billyshambrook** [comment]
I would also like to know the reason for this. We are currently doing the above workaround but because it's a private function, it seems like there was a specific design reason why this wasn't exposed :) thanks

**Comment by tianchu** [comment]
`lambda_metric` uses distributions for the following reasons:

- Only one data point per second is kept for a non-distribution metric (gauge, increment, etc) with the same tag set. E.g., when two lambda functions both trying to increment metric `hello.world` with tag `service:helloworld` by `10` on the same second, the metric will only be incremented by 10, instead of 20. This is not an issue in the serverful world, because the Datadog agent always tag the metric with a `host` tag, which separates out the time series from different hosts. 

- Distribution metrics enable TRUE histogram/percentiles view on the metric, comparing to the traditional histogram metric that is aggregated locally by the agent.

For distributions metric, you can actually make the decision on what type of metric it is at the graphing time, and you should be able to do whatever you were able to do with `gauge`, `increment` and `histogram`. E.g., if you can use `sum by` to graph the metric as if it was submitted by `increment`.

**Comment by ahmedezzeldin93** [comment]
Can I send guage custom metrics from AWS lambda using metrics python API `api.Metrics.send()`, without using datadog lambda layer ?

**Comment by tianchu** [comment]
@ahmedezzeldin93 technically speaking `api.Metrics.send()` should work, but I would recommend using lambda layer (built on top of [threadstats](https://docs.datadoghq.com/developers/faq/is-there-an-alternative-to-dogstatsd-and-the-api-to-submit-metrics-threadstats/)) though for following reasons:

- `api.Metrics.send()` blocks your code execution until api request completes. Threadstats and lambda layer flush metrics asynchronously in a background thread.
- `api.Metrics.send()` make a new request for every data point. Threadstats and lambda layer buckets adn aggregates metrics and only flush every 10 seconds.
- Threadstats doesn't guarantee a final flush when your lambda function exits, while lambda layer does.

If your use case doesn't care about local aggregation/bucketing and blocking api calls, `api.Metrics.send()` should work fine.

**Comment by dabcoder** [comment]
Thanks for following up with this issue @tianchu. Closing this for now then.
