### ISSUE TITLE
Feature request: configure underlying metric used by `statsd.timer`

### ISSUE THREAD

**Issue by zhammer** [DataDog/datadogpy#563]
Hey datadog team! I'm curious what y'all think of making it so that folks can configure the underlying metruc used by `statsd.timer`. I just got off a call with our org's datadog reps and it seems that using `distribution` instead of `histogram` metrics for timers would be better for our orgs use cases.

The changes needed seem fairly straightforward: the desired metric could be passed into `DogStatsd` -> `TimedContextManagerDecorator` and then used to configure the metric `TiemContextManagerDecorator` uses to emit the timer stats:
https://github.com/DataDog/datadogpy/blob/0cb37942d2aa3250aaf4a3225982f4f44634c466/datadog/dogstatsd/context.py#L75

Also on a related note, I'm a little confused that `TimedContextManagerDecorator` emits a `self.statsd.timing` rather than ` self.statsd.histogram` as [suggested by the docs](https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=python#timer)

**Comment by zhammer** [comment]
Happy to open a PR and QA on our end if this is something you're interested in!

**Comment by zhammer** [comment]
doing a quick local qa of this here: https://github.com/seatgeek/datadogpy/commit/87d3c866679df1e9d02471f1621b1c8204c34710

**Comment by jbarciauskas** [comment]
@zhammer I think the best approach would be just to create a new decorator that calls statsd.distribution, would that work?

**Comment by hush-hush** [comment]
Hi @zhammer,

I agree that the feature would be very useful.

First of, to answer your question about `timing` vs `histogram`, Dogstatsd is an extension of the statsd protocol (we added things like `event`, `service_check`, `distribution`, ...), we're trying to remain compatible with the base protocol. That way statsd app can send metrics to Datadog through the Agent. Timing, or `ms`, is a `statsd` metric type but in the Agent it's aggregated and interpretated just like an histogram (it happens [here](https://github.com/DataDog/datadog-agent/blob/5470cfeb2433975e5be327cc397582366a1c91cc/pkg/dogstatsd/enrich.go#L70) if you're interested). That's what we mean by `TIMER from StatsD is a sub-set of HISTOGRAM in DogStatsD` in the documentation.

For the implementation we're always happy to receive PR. I agree with @jbarciauskas that a new decorator might be better. Any reason/use case where you might want to switch an entire application from histogram to distribution instead of choosing per `TIMER` call ?

**Comment by jbarciauskas** [comment]
Hi @zhammer - is this something you're still interested in?

**Comment by zhammer** [comment]
Hey @jbarciauskas! This is definitely still something our team is interested in. I've been a bit busy with some other work and forgot to respond.

@hush-hush - that is a very helpful description, thank you :) also, cool to see where that is actually happening in the agent code.

> Any reason/use case where you might want to switch an entire application from histogram to distribution instead of choosing per TIMER call ?

Choosing per TIMER call seems good to me. I realize that even to migrate from using histogram to distribution timers in our apps, we may want to migrate specific timers/metrics in phases, so one global toggle for distribution vs. histogram would be tough. The only pros of using a global toggle I can think of would be:
1) the datadog statsd methods stay in sync with the standard python statsd methods: https://statsd.readthedocs.io/en/v3.3/timing.html#using-a-context-manager
2) devs on a codebase don't have to be aware of the underlying timer metric. they just add a timer and we've configured all timers to use (or at least default to) distributions. that way there isn't accidental sprawl of histogram vs distribution timers in one codebase.

> For the implementation we're always happy to receive PR.

Happy to work on a PR, but this work is a bit lower priority at the moment so it could be some time until I have a PR to share.

**Comment by dnlserrano** [comment]
Also very much interested in this. 🤓 I agree a specific decorator could work just fine (e.g., `with statsd.distributed(...)`), but I empathise with the suggestion from @zhammer of extending the `statsd.timer` existing one with an option for the desired timer metric, especially given this:

> devs on a codebase don't have to be aware of the underlying timer metric

**Comment by hush-hush** [comment]
First step will be a new decorator and then we can work on a global switch.

Right now I'm quite busy on other project but will come back to this as soon as I can (I'll create a card in our backlog to keep track of this). If this is a urgent matter I would be more than happy to review a PR !

**Comment by dnlserrano** [comment]
Opened PR #581.
