### ISSUE TITLE
Disable EC2/EKS tags from statsd custom metric ingestion

### ISSUE THREAD

**Issue by kencieszykowski** [DataDog/datadogpy#765]
Hey everyone,

Apologies for the blank issue type-- this is more of a 'help wanted' question than anything.  Have been searching around for a solution to this, and can't quite nail it down.

In any case-- we are running pods in `EKS v1.23`, and creating a fair amount of custom metrics.  All of these metrics are getting EC2 metadata tags applied to them, rather than the four or five tags that we've isolated in our class. 

I've combed through the docs here, and can't quite figure out if this is due to Autodiscovery on our agent, or how we are able to configure this when we initialize statsd to _exclude_ the 30+ tags that are getting added (`security-group`,`aws`, etc.).

Any insight would be much appreciated.

**Comment by sgnn7** [comment]
Hey @kencieszykowski!

This is probably a question for Datadog support but overall theres generally 2 things that add those extra tags: Agent and AWS integration. You can use [`exclude_ec2_tags`](https://github.com/DataDog/datadog-agent/blob/a2b733312053191859ad6bf773f520b69377efb3/pkg/config/config_template.yaml#L378-L382) for the Agent and https://docs.datadoghq.com/account_management/billing/aws/#aws-resource-exclusion for the AWS integration side.

I'll close this issue for now since that should solve it for you but feel free to reopen if needed.
